package com.github.natalyjaya.jetflo.ci

import com.github.natalyjaya.jetflo.ui.RockyWidget
import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.project.Project
import com.intellij.openapi.vfs.LocalFileSystem
import com.intellij.openapi.vfs.VfsUtil
import java.io.File
import java.time.Instant
import javax.swing.SwingUtilities

class CodeBundleGenerator(private val project: Project) {
    private val allowedExtensions = setOf(
        "kt", "java", "xml", "kts", "gradle", "md", "properties",
        "yml", "yaml", "json", "ts", "js", "py", "swift", "go", "rs"
    )
    private val ignoredDirs = setOf(
        "build", ".gradle", ".idea", ".git", "node_modules",
        "dist", ".next", "coverage", "__pycache__"
    )
    private val sensitiveKeys = setOf(
        "password", "secret", "token", "api_key", "apikey",
        "private_key", "access_key", "auth"
    )

    fun generate(onFinished: (() -> Unit)? = null) {
        SwingUtilities.invokeLater {
            RockyWidget.instance?.showMessage("Reading project...\nThis may take a bit!")
        }
        Thread {
            try {
                val basePath = project.basePath ?: return@Thread
                val baseDir  = File(basePath)
                val files    = collectFiles(baseDir)

                if (files.isEmpty()) {
                    SwingUtilities.invokeLater {
                        RockyWidget.instance?.showMessage("No files found\nto bundle.")
                        onFinished?.invoke()
                    }
                    return@Thread
                }

                SwingUtilities.invokeLater {
                    RockyWidget.instance?.showMessage("Bundling ${files.size} files...\nAlmost there!")
                }

                val markdown = buildBundle(baseDir, files)
                val outputFile = File("$basePath/CODEBUNDLE.md").apply { writeText(markdown) }

                ApplicationManager.getApplication().invokeLater {
                    LocalFileSystem.getInstance().refreshAndFindFileByIoFile(outputFile)?.let { vf ->
                        VfsUtil.markDirtyAndRefresh(false, false, false, vf)
                    }
                    RockyWidget.instance?.showMessage("Done!\nCheck CODEBUNDLE.md")
                    onFinished?.invoke()
                }

            } catch (e: Exception) {
                SwingUtilities.invokeLater {
                    RockyWidget.instance?.showMessage("Error: ${e.message?.take(40)}")
                    onFinished?.invoke()
                }
            }
        }.apply { isDaemon = true; start() }
    }

    private fun collectFiles(baseDir: File): List<File> =
        baseDir.walkTopDown()
            .filter { file ->
                file.isFile &&
                        file.extension in allowedExtensions &&
                        file.path.split(File.separator).none { it in ignoredDirs } &&
                        file.length() < 5_000_000
            }
            .take(10_000)
            .toList()

    private fun buildBundle(baseDir: File, files: List<File>): String {
        val basePath = baseDir.absolutePath
        return buildString {
            appendLine("# CodeBundle: ${baseDir.name}")
            appendLine("Generated: ${Instant.now()}")
            appendLine("Root: $basePath")
            appendLine("Files: ${files.size}")
            appendLine()
            appendLine("## How to apply changes")
            appendLine("- Return changes as **unified diffs** per file whenever possible.")
            appendLine("- Files are delimited with `` markers.")
            appendLine()
            appendLine("## Project tree")
            appendLine("```")
            appendLine(buildTree(baseDir, files))
            appendLine("```")
            appendLine()
            appendLine("## Files list")
            files.forEach { file ->
                val rel  = file.path.removePrefix("$basePath/")
                val size = formatSize(file.length())
                appendLine("- `$rel` ($size)")
            }
            appendLine()
            appendLine("---")
            files.forEach { file ->
                val rel = file.path.removePrefix("$basePath/")
                appendLine("")
                appendLine("## $rel")
                appendLine()
                appendLine("```${file.extension}")
                appendLine(redact(file.readText()))
                appendLine("```")
                appendLine("")
                appendLine()
                appendLine("---")
            }
            appendLine("## Bundle notes")
            appendLine("- Redaction: enabled (mask: `***REDACTED***`).")
            appendLine("- Generated by JetFlo plugin.")
        }
    }

    private fun buildTree(baseDir: File, files: List<File>): String {
        val basePath = baseDir.absolutePath
        val paths    = files.map { it.path.removePrefix("$basePath/") }
        val tree     = StringBuilder()
        val dirs = mutableSetOf<String>()

        paths.forEach { path ->
            val parts = path.split("/")
            for (i in 1 until parts.size) {
                dirs.add(parts.take(i).joinToString("/"))
            }
        }

        val allEntries = (dirs.map { it to true } + paths.map { it to false })
            .sortedBy { it.first }

        allEntries.forEach { (entry, isDir) ->
            val depth  = entry.count { it == '/' }
            val indent = "│  ".repeat(depth)
            val name   = entry.substringAfterLast('/')
            val prefix = if (isDir) "├─ $name/" else "├─ $name"
            tree.appendLine("$indent$prefix")
        }
        return tree.toString().trimEnd()
    }

    private fun redact(content: String): String {
        var result = content
        sensitiveKeys.forEach { key ->
            val regex = Regex("""(?i)($key\s*[=:]\s*)["']?([^\s"'\n,}]+)["']?""")
            result = regex.replace(result) { mr ->
                "${mr.groupValues[1]}***REDACTED***"
            }
        }
        result = result.replace(Regex("""Bearer\s+[A-Za-z0-9\-._~+/]+=*"""), "Bearer ***REDACTED***")
        result = result.replace(Regex("""AKIA[0-9A-Z]{16}"""), "***REDACTED***")
        return result
    }

    private fun formatSize(bytes: Long): String = when {
        bytes < 1024 -> "$bytes bytes"
        bytes < 1024 * 1024 -> "${bytes / 1024} KB"
        else -> "${bytes / (1024 * 1024)} MB"
    }
}